In [1]:
!pip install --user imbalanced-learn

In [35]:
from imblearn.over_sampling import SMOTE

In [36]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
import seaborn as sns
%matplotlib inline
from sklearn.naive_bayes import BernoulliNB
from sklearn.tree import DecisionTreeClassifier
import numpy as np

In [3]:
dados = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/ML_Classificacao_por_tras_dos_panos/main/Dados/Customer-Churn.csv')

In [4]:
dados.head()

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo  \
0            0     Sim         Nao                1          Nao   
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   
3            0     Nao         Nao               45          Nao   
4            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline  \
0    SemServicoTelefonico               DSL             Nao          Sim   
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   
3    SemServicoTelefonico               DSL             Sim          Nao   
4                     Nao       FibraOptica             Nao          Nao   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato  \
0                 Nao            Nao     Nao               Nao    Mensalmente   
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   
3                 Sim            Sim     Nao               Nao          UmAno   
4                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim  
3             Nao    DebitoEmConta        42.30   Nao  
4             Sim    ChequeDigital        70.70   Sim

In [5]:
traducao_dic = {'Sim':1, 'Nao':0}
dados_modificados = dados [['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn']].replace(traducao_dic)

In [6]:
dados_modificados.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1
3        0            0             0                0      0
4        0            0             1                1      1

In [7]:
dummie_dados = pd.get_dummies(dados.drop(['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn'], axis=1))

In [8]:
dados_final = pd.concat([dados_modificados,dummie_dados], axis=1)

In [38]:
smt = SMOTE(random_state=123)
x, y = smt.fit_resample(x, y)

In [39]:
dados_final = pd.concat([x, y], axis=1)

In [40]:
dados_final.Churn.value_counts()

0    5174
1    5174
Name: Churn, dtype: int64

In [41]:
dados_final.shape

(10348, 39)

In [42]:
x = dados_final.drop(columns = 'Churn')

In [43]:
x.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Maior65Anos  \
0        1            0             0                1            0   
1        0            0             1                0            0   
2        0            0             1                1            0   
3        0            0             0                0            0   
4        0            0             1                1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  VariasLinhasTelefonicas_Sim  \
0                                             1                            0   
1                                             0                            0   
2                                             0                            0   
3                                             1                            0   
4                                             0                            0   

   ...  StreamingDeFilmes_Nao  StreamingDeFilmes_SemServicoDeInternet  \
0  ...                      1                                       0   
1  ...                      1                                       0   
2  ...                      1                                       0   
3  ...                      1                                       0   
4  ...                      1                                       0   

   StreamingDeFilmes_Sim  TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  \
0                      0                        0                           1   
1                      0                        0                           0   
2                      0                        0                           1   
3                      0                        0                           0   
4                      0                        0                           1   

   TipoDeContrato_UmAno  FormaDePagamento_CartaoDeCredito  \
0                     0                                 0   
1                     1                                 0   
2                     0                                 0   
3                     1                                 0   
4                     0                                 0   

   FormaDePagamento_ChequeDigital  FormaDePagamento_ChequePapel  \
0                               1                             0   
1                               0                             1   
2                               0                             1   
3                               0                             0   
4                               1                             0   

   FormaDePagamento_DebitoEmConta  
0                               0  
1                               0  
2                               0  
3                               1  
4                               0  

[5 rows x 38 columns]

In [44]:
y = dados_final['Churn']
y.head()

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

In [45]:
norm = StandardScaler()
x_normalizado = norm.fit_transform(x)
x_normalizado


array([[ 1.26542767, -0.52756038, -3.06083934, ...,  1.30292044,
        -0.47882211, -0.4360152 ],
       [-0.79024667, -0.52756038,  0.32670777, ..., -0.76750657,
         2.08845829, -0.4360152 ],
       [-0.79024667, -0.52756038,  0.32670777, ..., -0.76750657,
         2.08845829, -0.4360152 ],
       ...,
       [-0.79024667, -0.52756038,  0.32670777, ...,  1.30292044,
        -0.47882211, -0.4360152 ],
       [-0.79024667, -0.52756038,  0.32670777, ..., -0.76750657,
        -0.47882211, -0.4360152 ],
       [-0.79024667, -0.52756038,  0.32670777, ..., -0.76750657,
        -0.47882211, -0.4360152 ]])

In [46]:
X_train, X_test, y_train, y_test = train_test_split(x_normalizado,y, test_size=0.3,random_state=123)

In [47]:
knn = KNeighborsClassifier(metric='euclidean')

In [48]:
knn.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean')

In [49]:
predito_knn = knn.predict(X_test)

In [50]:
predito_knn

array([1, 0, 0, ..., 0, 1, 1], dtype=int64)

In [51]:
np.median(X_train)

-0.4461759755508453

In [52]:
bnb = BernoulliNB(binarize=-0.44)

In [53]:
bnb.fit(X_train, y_train)

BernoulliNB(binarize=-0.44)

In [54]:
predito_bnb = bnb.predict(X_test)

In [55]:
predito_bnb

array([1, 0, 0, ..., 1, 1, 1], dtype=int64)

In [56]:
accuracy_score(y_test, predito_bnb)

0.7549114331723027

In [57]:
dtc = DecisionTreeClassifier(criterion='entropy', random_state=42)
dtc.fit(X_train, y_train)


DecisionTreeClassifier(criterion='entropy', random_state=42)

In [58]:
dtc.feature_importances_

array([0.02070208, 0.01349543, 0.0068095 , 0.02090223, 0.01492519,
       0.16169616, 0.22580293, 0.00889189, 0.00344576, 0.01122927,
       0.0019815 , 0.03128648, 0.00065123, 0.01251806, 0.        ,
       0.0145619 , 0.00784856, 0.        , 0.0097366 , 0.01125643,
       0.        , 0.00735279, 0.0143391 , 0.00396098, 0.01956256,
       0.00262135, 0.        , 0.00203258, 0.0082409 , 0.0003825 ,
       0.01088157, 0.03622159, 0.16358635, 0.07445054, 0.01664409,
       0.02129506, 0.02179021, 0.01889663])

In [59]:
predito_decision_tree = dtc.predict(X_test)

In [60]:
predito_decision_tree

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [61]:
accuracy_score(y_test,predito_decision_tree )

0.8074074074074075

In [62]:
print('Método KNN')
print(f'Acurácia: {(accuracy_score(y_test,predito_knn)*100).round(2)}%')
print(f'Precisão: {(precision_score(y_test,predito_knn)*100).round(2)}%')
print(f'Recall Score: {(recall_score(y_test,predito_knn)*100).round(2)}%')
print('Matriz de confusão')
print(confusion_matrix(y_test,predito_knn))

Método KNN
Acurácia: 81.35%
Precisão: 79.67%
Recall Score: 83.66%
Matriz de confusão
[[1241  328]
 [ 251 1285]]


In [63]:
print('Método Bnb')
print(f'Acurácia: {(accuracy_score(y_test,predito_bnb)*100).round(2)}%')
print(f'Precisão: {(precision_score(y_test,predito_bnb)*100).round(2)}%')
print(f'Recall Score: {(recall_score(y_test,predito_bnb)*100).round(2)}%')
print('Matriz de confusão')
print(confusion_matrix(y_test,predito_bnb))

Método Bnb
Acurácia: 75.49%
Precisão: 71.37%
Recall Score: 84.24%
Matriz de confusão
[[1050  519]
 [ 242 1294]]


In [64]:
print('Método Árvore de Decisão')
print(f'Acurácia: {(accuracy_score(y_test,predito_decision_tree)*100).round(2)}%')
print(f'Precisão: {(precision_score(y_test,predito_decision_tree)*100).round(2)}%')
print(f'Recall Score: {(recall_score(y_test,predito_decision_tree)*100).round(2)}%')
print('Matriz de confusão')
print(confusion_matrix(y_test,predito_decision_tree))

Método Árvore de Decisão
Acurácia: 80.74%
Precisão: 79.76%
Recall Score: 81.84%
Matriz de confusão
[[1250  319]
 [ 279 1257]]
